/**
 * Capability-card storage. Nearly every test here is about the same invariant
 * from a different angle: a regenerated card must not destroy a hand
 * correction, and a hand correction must not be able to lie about provenance.
 * That tension is the whole reason the card is stored in two halves.
 */
import {
  type CapabilityCard,
  type Model,
  ModelIdSchema,
  type Provider,
  ProviderIdSchema,
} from "@rewter/shared";
import { beforeEach, describe, expect, it } from "vitest";
import { EventBus } from "../events/bus.js";
import { type Db, openDb } from "./connection.js";
import { Repos } from "./repos.js";

const mdl = ModelIdSchema.parse("zai/glm-5.3");
const prv = ProviderIdSchema.parse("prv_zaixxx000000");

let db: Db;
let repos: Repos;
let tick: number;

beforeEach(() => {
  db = openDb(":memory:");
  tick = 1_724_800_000_000;
  const clock = () => ++tick;
  repos = new Repos(db, new EventBus(db, clock), clock);
  repos.upsertProvider(provider());
  repos.upsertModel(model());
});

function provider(): Provider {
  return {
    id: prv,
    name: "Z.AI",
    kind: "openai-compat",
    baseUrl: "https://api.z.ai/api/paas/v4",
    apiKeyRef: "ZAI_API_KEY",
    enabled: true,
    createdAt: tick,
    updatedAt: tick,
  };
}

function model(): Model {
  return {
    id: mdl,
    providerId: prv,
    upstreamId: "glm-5.3",
    displayName: "GLM 5.3",
    contextWindow: 200_000,
    maxOutputTokens: 8192,
    pricing: {
      inputPerMTok: 0.6,
      outputPerMTok: 2.2,
      cacheReadPerMTok: null,
      cacheWritePerMTok: null,
    },
    modalities: ["text"],
    supports: { tools: true, streaming: true, vision: false, caching: false },
    source: "manual",
    enabled: true,
    createdAt: tick,
    updatedAt: tick,
  };
}

function card(over: Partial<CapabilityCard> = {}): CapabilityCard {
  return {
    modelId: mdl,
    summary: "fast general-purpose model",
    strengths: ["coding", "fast_cheap"],
    weaknesses: ["vision"],
    bestAt: ["coding"],
    notes: null,
    userOverrides: null,
    generatedBy: ModelIdSchema.parse("anthropic/claude-sonnet-5"),
    generatedAt: tick,
    updatedAt: tick,
    ...over,
  };
}

describe("capability card storage", () => {
  it("round-trips a card, tag arrays included", () => {
    const written = repos.upsertCard(card());
    expect(repos.getCard(mdl)).toEqual(written);
    expect(written.strengths).toEqual(["coding", "fast_cheap"]);
  });

  it("returns undefined for a model with no card", () => {
    expect(repos.getCard(ModelIdSchema.parse("openai/gpt-9"))).toBeUndefined();
  });

  it("lists cards sorted by model id", () => {
    repos.upsertModel({ ...model(), id: ModelIdSchema.parse("zai/glm-4") });
    repos.upsertCard(card());
    repos.upsertCard(card({ modelId: ModelIdSchema.parse("zai/glm-4") }));
    expect(repos.listCards().map((c) => c.modelId)).toEqual(["zai/glm-4", "zai/glm-5.3"]);
  });

  // ── The override contract ─────────────────────────────────────────────────

  it("applies overrides over generated fields on read", () => {
    repos.upsertCard(card());
    const merged = repos.setCardOverrides(mdl, { summary: "actually mediocre at code" });

    expect(merged.summary).toBe("actually mediocre at code");
    // Untouched fields still come from the generated half.
    expect(merged.strengths).toEqual(["coding", "fast_cheap"]);
  });

  it("survives a re-sync: regenerating the card keeps the override", () => {
    repos.upsertCard(card());
    repos.setCardOverrides(mdl, { bestAt: ["fast_cheap"] });

    // What `sync-models` / card regeneration does — a full upsert of generated
    // content, with no knowledge that an override exists.
    repos.upsertCard(card({ summary: "regenerated", bestAt: ["reasoning"] }));

    const merged = repos.getCard(mdl);
    expect(merged?.summary).toBe("regenerated"); // generated half updated…
    expect(merged?.bestAt).toEqual(["fast_cheap"]); // …override still on top.
  });

  it("replaces a list rather than appending to it", () => {
    // "This list is wrong" is the common correction; an append could never
    // express a deletion.
    repos.upsertCard(card());
    const merged = repos.setCardOverrides(mdl, { strengths: ["math"] });
    expect(merged.strengths).toEqual(["math"]);
  });

  it("clearing the override restores the generated card", () => {
    repos.upsertCard(card());
    repos.setCardOverrides(mdl, { summary: "hand-written" });
    expect(repos.setCardOverrides(mdl, null).summary).toBe("fast general-purpose model");
  });

  it("refuses to set overrides on a model with no card", () => {
    expect(() => repos.setCardOverrides(mdl, { summary: "x" })).toThrow(/no capability card/);
  });

  it("does not let an override rewrite provenance", () => {
    // A card that claims it was generated by a model that never saw it is a
    // record that lies about itself.
    repos.upsertCard(card());
    const merged = repos.setCardOverrides(mdl, {
      modelId: "openai/gpt-9",
      generatedBy: "openai/gpt-9",
      generatedAt: 1,
      summary: "ok",
    });

    expect(merged.modelId).toBe(mdl);
    expect(merged.generatedBy).toBe("anthropic/claude-sonnet-5");
    expect(merged.summary).toBe("ok"); // the legitimate part still applied
  });

  it("ignores an override that would produce an invalid card", () => {
    // A hand-edit with a typo'd tag must not take the model out of the registry.
    repos.upsertCard(card());
    const merged = repos.setCardOverrides(mdl, { strengths: ["definitely-not-a-tag"] });
    expect(merged.strengths).toEqual(["coding", "fast_cheap"]);
  });

  it("exposes the unmerged card for the editor", () => {
    repos.upsertCard(card());
    repos.setCardOverrides(mdl, { summary: "hand-written" });

    const raw = repos.getRawCard(mdl);
    expect(raw?.summary).toBe("fast general-purpose model");
    expect(raw?.userOverrides).toEqual({ summary: "hand-written" });
  });

  it("deletes a card without touching the model", () => {
    repos.upsertCard(card());
    repos.deleteCard(mdl);
    expect(repos.getCard(mdl)).toBeUndefined();
    expect(repos.getModel(mdl)).toBeDefined();
  });
});
