/**
 * `rewter install-service` — the launchd plist, and why it is this shape.
 *
 * launchd is the only supported supervisor because rewter is a *local* daemon on
 * a *personal* machine: it holds the user's provider keys, listens on loopback,
 * and should come back after a reboot without anyone typing anything. That is
 * exactly a LaunchAgent, and nearly the whole design falls out of two facts
 * about how launchd starts things:
 *
 * 1. **The environment is nearly empty.** No `~/.zshrc`, so no `ANTHROPIC_API_KEY`,
 *    and often no usable `PATH`. Keys are therefore not in the plist at all —
 *    they come from `~/.rewter/env` (see `config/envfile.ts`), a file with a
 *    mode we can check, rather than from a plist that `launchctl print` will
 *    happily read back to anyone. `ProgramArguments` names an absolute node
 *    binary for the same reason: there is no PATH to search.
 *
 * 2. **launchd wants the process to stay in the foreground.** A daemon that
 *    forks and exits looks like a crash to it. `rewter start` already runs in
 *    the foreground, so it is the command the plist runs, unchanged — the same
 *    one a person types, which means the launchd path is not a second code path
 *    that can rot untested.
 *
 * `KeepAlive` is deliberately *conditional* (`SuccessfulExit: false`) rather
 * than `true`: a daemon that exits 0 was asked to stop — by `rewter stop`, or by
 * SIGTERM at logout — and restarting it a second later would make `stop` appear
 * broken. A non-zero exit is a crash, and that we do want restarted, throttled
 * so a config error becomes a slow retry loop in the log rather than a spin.
 *
 * Writing the file is not loading it. `install-service` writes and then tells
 * the user the two `launchctl` lines to run, rather than shelling out itself:
 * `bootstrap` needs the right domain target for the current session, it fails in
 * ways worth reading, and a tool that silently ran privileged-ish commands on
 * your behalf is not what you want holding your API keys.
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

/** Reverse-DNS, matching the convention every other agent in `~/Library/LaunchAgents` uses. */
export const SERVICE_LABEL = "com.roowus.rewter";

/** Where the daemon's stdout and stderr land. `logs` reads the same paths. */
export const LOG_DIR = "~/Library/Logs/rewter";

export interface PlistOptions {
  /** Absolute path to the node binary — there is no PATH to search under launchd. */
  nodePath: string;
  /** Absolute path to the CLI entry point (`packages/cli/dist/index.js`). */
  cliPath: string;
  /** Expanded `~/Library/Logs/rewter`. */
  logDir: string;
  /** Passed through as `--config`, when the user runs on a non-default one. */
  configPath?: string | undefined;
  /** `WorkingDirectory`. Defaults to the user's home. */
  workingDirectory?: string | undefined;
}

/**
 * Render the plist.
 *
 * Kept as a pure string function so the interesting parts — no secrets, an
 * absolute node, conditional KeepAlive — are assertable without touching
 * `~/Library`.
 */
export function renderPlist(opts: PlistOptions): string {
  const args = [opts.nodePath, opts.cliPath, "start"];
  if (opts.configPath !== undefined) args.push("--config", opts.configPath);

  const argXml = args.map((a) => `    <string>${escapeXml(a)}</string>`).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  rewter — generated by \`rewter install-service\`.

  API keys are NOT here on purpose: they live in ~/.rewter/env, which rewter
  reads at boot and whose permissions it checks. Anything in this file is
  readable by \`launchctl print\`.
-->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${SERVICE_LABEL}</string>

  <key>ProgramArguments</key>
  <array>
${argXml}
  </array>

  <key>RunAtLoad</key>
  <true/>

  <!-- Restart a crash, but not a clean exit: exit 0 means \`rewter stop\` asked
       it to go, and bringing it back would make \`stop\` look broken. -->
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>

  <!-- A config error should be a slow retry in the log, not a spin. -->
  <key>ThrottleInterval</key>
  <integer>10</integer>

  <key>WorkingDirectory</key>
  <string>${escapeXml(opts.workingDirectory ?? dirname(opts.logDir))}</string>

  <key>StandardOutPath</key>
  <string>${escapeXml(join(opts.logDir, "rewter.log"))}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(join(opts.logDir, "rewter.err.log"))}</string>

  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
`;
}

export interface InstallOptions extends PlistOptions {
  /** Where the plist goes — `~/Library/LaunchAgents/com.roowus.rewter.plist`. */
  plistPath: string;
  /** Print the file instead of writing it. */
  dryRun?: boolean;
  /** Rewrite an existing plist. Without it, an existing file is left alone. */
  force?: boolean;
}

export interface InstallResult {
  plistPath: string;
  contents: string;
  /** What happened: nothing (dry run), a fresh write, a rewrite, or a refusal. */
  action: "written" | "replaced" | "unchanged" | "exists" | "dry-run";
  /** The `launchctl` lines the user still has to run, in order. */
  next: string[];
}

/**
 * Write the plist, or say why it did not.
 *
 * An existing plist is not overwritten without `--force`: people hand-edit these
 * (an extra `EnvironmentVariables` key, a different label) and silently
 * discarding that is the kind of helpfulness nobody asks for twice. An existing
 * file whose contents already match is reported as `unchanged` rather than
 * `exists`, so re-running after an upgrade is quiet when nothing moved.
 */
export function installService(opts: InstallOptions): InstallResult {
  const contents = renderPlist(opts);
  const next = launchctlSteps(opts.plistPath);

  if (opts.dryRun === true) {
    return { plistPath: opts.plistPath, contents, action: "dry-run", next };
  }

  const existing = existsSync(opts.plistPath) ? readSafely(opts.plistPath) : undefined;
  if (existing !== undefined) {
    if (existing === contents) {
      return { plistPath: opts.plistPath, contents, action: "unchanged", next };
    }
    if (opts.force !== true) {
      return { plistPath: opts.plistPath, contents, action: "exists", next };
    }
  }

  mkdirSync(dirname(opts.plistPath), { recursive: true });
  // The log directory too: launchd will not create it, and a StandardOutPath it
  // cannot open makes the job fail with nowhere to say so.
  mkdirSync(opts.logDir, { recursive: true });
  writeFileSync(opts.plistPath, contents);

  return {
    plistPath: opts.plistPath,
    contents,
    action: existing === undefined ? "written" : "replaced",
    next,
  };
}

/** Remove the plist. Unloading it first is the user's `launchctl bootout`. */
export function uninstallService(plistPath: string): { removed: boolean; next: string[] } {
  const removed = existsSync(plistPath);
  rmSync(plistPath, { force: true });
  return {
    removed,
    next: removed ? [`launchctl bootout gui/$(id -u)/${SERVICE_LABEL}`] : [],
  };
}

/**
 * The two lines to run, with `bootout` first.
 *
 * `bootstrap` on an already-loaded label fails with a bare error code rather
 * than a message, and re-running `install-service` after an upgrade is the
 * common case, so unloading first is the honest instruction. `|| true` because
 * on a first install there is nothing to unload and the failure is expected.
 */
function launchctlSteps(plistPath: string): string[] {
  return [
    `launchctl bootout gui/$(id -u)/${SERVICE_LABEL} 2>/dev/null || true`,
    `launchctl bootstrap gui/$(id -u) ${plistPath}`,
  ];
}

function readSafely(path: string): string | undefined {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return undefined;
  }
}

/** Paths can contain `&` and `<`; a plist that does not escape them will not parse. */
function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
